services:
  app:
    build:
      context: .
      target: runner
    image: henrotaym/laravel-trustup-io-deployment-runner:local
    volumes:
      - ./:/opt/apps/app
    ports:
      - ${VITE_PORT:-8000}:${VITE_PORT:-8000}

  cli:
    build:
      context: .
      target: cli
    image: henrotaym/laravel-trustup-io-deployment-cli:local
    volumes:
      - ./:/opt/apps/app
    profiles:
      - cli
