#!/bin/bash

run() {
    docker compose run --rm \
        {{{{appKey}}}}-cli \
        "$@"
}

runWithPorts() {
    docker compose run --rm --service-ports \
        {{{{appKey}}}}-cli \
        "$@"
}

if [ "$1" == "root" ]
    then
        script="$2"
        folder=$(echo $PWD | sed -e 's/.\+\/projects\///g')
        parameters=$folder
        if [ $3 ]
            then
                parameters=${@:3}
        fi

        cd ../../
        ./cli $script $parameters
        cd $PWD
    exit
fi

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
    exit
fi

if [ "$1" == "start" ]
    then
        ./scripts/start.sh $2
    exit
fi

if [ "$1" == "stop" ]
    then
        ./scripts/stop.sh
    exit
fi

if [ "$1" == "restart" ]
    then
        ./scripts/restart.sh $2
    exit
fi

if [ "$1" == "artisan" ]
    then
        ./cli php artisan ${@:2}
    exit
fi

if [ "$1" == "test" ]
    then
        args="${@:2}"
        run ./vendor/bin/phpunit "$args"
    exit
fi

if [ "$1" == "testf" ]
    then
        ./cli test --filter="'${*:2}'"
    exit
fi

if [ "$1" == "testg" ]
    then
        ./cli test --group="'${*:2}'"
    exit
fi

if [ "$1" == "format" ]
    then
        ./cli ./vendor/bin/pint ${@:2}
    exit
fi

if [ "$1" == "analyze" ]
    then
        ./cli ./vendor/bin/phpstan analyse ${@:2}
    exit
fi

if [ "${*:2}" == "run dev" ]
    then
        runWithPorts $@
    exit
fi

run "$@"