#!/bin/bash

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
    exit
fi

if [ "$1" == "start" ]
    then
        ./scripts/start.sh $2
    exit
fi

if [ "$1" == "stop" ]
    then
        ./scripts/stop.sh
    exit
fi

if [ "$1" == "restart" ]
    then 
        ./scripts/restart.sh $2
    exit
fi

./vendor/bin/sail "$@"