name: Linter

on:
  push:
    branches:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Lint code
        run: pnpm lint
